name: SB-Skylands
version: "1.11"
main: de.sirati97.sb.skylands.SkylandsPlugin
description: The SB-Skylands Generator for 1.13
author: Jenkins
authors: ['Other Authors of SkylandsPlus','sirati97','Sleaker']
load: startup
api-version: 1.13
commands:
    debug-multicore-generation:
        description: 'prints out debug information of the multicore genertor'
        usage: '<command> [world]'
        permission: sb.skylands.debug
permissions:
   sb.skylands.debug:
       default: op